#!/usr/bin/env bash

killall -q polybar

# Get the count of connected displays
DISPLAY_COUNT=$(xrandr --query | grep ' connected' | wc -l)

echo "---" | tee -a /tmp/polybar-primary.log

# Always start primary polybar
polybar --config=$HOME/.config/polybar/config.ini primary 2>&1 | tee -a /tmp/polybar-primary.log & disown

# If more than one display is connected, start the other bars as well
if [ "$DISPLAY_COUNT" -gt 1 ]; then
    echo "---" | tee -a /tmp/polybar-vertical.log /tmp/polybar-laptop.log
    polybar --config=$HOME/max/.config/polybar/config.ini vertical 2>&1 | tee -a /tmp/polybar-vertical.log & disown
    polybar --config=$HOME/max/.config/polybar/config.ini laptop 2>&1 | tee -a /tmp/polybar-laptop.log & disown
fi
