import = [
  "~/.config/alacritty/themes/kit.toml"
  # "~/.config/alacritty/themes/alacritty-theme/themes/rose-pine-dawn.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"
