[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[general]
import = [
  #"~/.config/alacritty/themes/kit.toml"
  #"~/.config/alacritty/themes/alacritty-theme/themes/github_dark_high_contrast.toml"
  #"~/.config/alacritty/themes/alacritty-theme/themes/github_light.toml"
  #"~/.config/alacritty/themes/alacritty-theme/themes/catppuccin_mocha.toml"
  "~/.config/alacritty/themes/alacritty-theme/themes/carbonfox.toml"
]
