#!/usr/bin/env sh
NUM_MONITORS=$(xrandr | grep " connected " | wc -l)

if [ $NUM_MONITORS -eq 1 ]; then
  TERMINAL_FONT_SIZE=11
else
  TERMINAL_FONT_SIZE=15
fi

alacritty --option font.size=$TERMINAL_FONT_SIZE

