#!/usr/bin/bash

set -e

device_label="$(\
  lsblk -o MOUNTPOINT,LABEL \
  | awk 'NR>1' \
  | grep -E '^\s+(\w+\s*)+' \
  | grep -E '^' \
  | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
  | dmenu -p 'Mount Drive:' -fn 'monospace:size=15' -l 10 \
  )"

device_path="$(blkid -L "$device_label" -o device)"

udisksctl mount -b "$device_path"
