#!/bin/sh

a="$(echo $(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name'))"

if [ "$1" = "left" ]; then
  i3-msg "focus output left; move workspace to output right; focus output right; workspace $a; move workspace to output left"
fi

if [ "$1" = "right" ]; then
  i3-msg "focus output right; move workspace to output left; focus output left; workspace $a; move workspace to output right"
fi

