#!/usr/bin/bash

set -e

device_label="$( \
  lsblk -o MOUNTPOINT,LABEL \
  | awk 'NR>1' \
  | grep -E '^(/\w+)+\s+(\w+\s*)+' \
  | sed 's/.*[[:space:]]\{2\}//g' \
  | dmenu -p 'Unmount Drive:' -fn 'monospace:size=15' -l 10 \
)"

device_path="$(blkid -L "$device_label" -o device)"

udisksctl unmount -b "$device_path"
