config:
    environment.DISPLAY: :1
    environment.XDG_RUNTIME_DIR: /home/ubuntu/1000
    nvidia.driver.capabilities: all
    nvidia.runtime: "false"
    raw.idmap: both 1000 1000
    user.user-data: |
        #cloud-config
        packages:
            - x11-apps
            - mesa-utils
description: GUI LXD profile
devices:
    X0:
        bind: container
        connect: unix:@/tmp/.X11-unix/X1
        listen: unix:@/tmp/.X11-unix/X1
        security.gid: "1000"
        security.uid: "1000"
        type: proxy
    mygpu:
        type: gpu
    u1000:
        path: /home/ubuntu/1000
        source: /run/user/1000
        type: disk
name: nvidia
used_by: [] 
