config:
  environment.DISPLAY: :0
  raw.idmap: both 1000 1000
description: ""
devices:
  X0:
    path: /tmp/.X11-unix/X0
    source: /tmp/.X11-unix/X1
    type: disk
name: dev
used_by:
- /1.0/instances/base-ros-focal
- /1.0/instances/base-ros-jammy
- /1.0/instances/fzi-ros-focal
- /1.0/instances/fzi-ros-jammy
- /1.0/instances/kitcar-ros-focal
- /1.0/instances/kitcar-ros-jammy
- /1.0/instances/anymal-simulation
- /1.0/instances/torch-boniki
- /1.0/instances/simopt
- /1.0/instances/minecraft
- /1.0/instances/fzi-boniki
- /1.0/instances/ros2-control
