export ZDOTDIR=$HOME/.config/zsh
. "$HOME/.cargo/env"
export PATH=$PATH:$HOME/.local/bin:$HOME/.config/i3/scripts:$HOME/.config/polybar/scripts
export TERMINAL=alacritty-wrapper
export BROWSER=brave-browser
export EDITOR=nvim
export WALLPAPER=$HOME/Pictures/Wallpapers/windows-xp-bliss-4k-lu-2560x1440.jpg
export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal
